### ISSUE TITLE
Unable to add a trackable

### ISSUE THREAD

**Issue by davyskiba** [ably/asset-tracking-backend-demo#12]
When adding a trackable to the publisher, I'm getting a `ConnectionException`  with `Unable to perform presence operation (permission denied) https://help.ably.io/error/40160` message. The corresponding order is already assigned to my rider on the backend, and the publisher is using an updated token.

I guess we might need some additional capabilities when creating the token on the backend side

Full exception stack trace:

```
com.ably.tracking.ConnectionException: Unable to perform presence operation (permission denied)
        at com.ably.tracking.common.AblyHelpersKt.toTrackingException(AblyHelpers.kt:55)
        at com.ably.tracking.common.DefaultAbly$enterPresenceSuspending$2$1.onError(Ably.kt:688)
        at io.ably.lib.transport.ConnectionManager$PendingMessageQueue.nack(ConnectionManager.java:1610)
        at io.ably.lib.transport.ConnectionManager.onNack(ConnectionManager.java:1182)
        at io.ably.lib.transport.ConnectionManager.onMessage(ConnectionManager.java:1070)
        at io.ably.lib.transport.WebSocketTransport$WsClient.onMessage(WebSocketTransport.java:183)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:641)
        at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:959)
        at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:912)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by davyskiba** [comment]
Resolved the issue by adding presence capability to the original ably key used by the backend, after the fix was merged
